name: Build Android APK
on:
  push:
    branches: [ "master", "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Free Disk Space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libltdl-dev libffi-dev libssl-dev libncurses5-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev libtool autoconf automake libtool-bin zlib1g-dev zip unzip

      - name: Install Buildozer
        run: pip install buildozer cython==0.29.33

      - name: Build APK
        working-directory: ./frontend
        run: |
          buildozer android clean
          yes | buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: getline-apk
          path: frontend/bin/*.apk