name: Build APK

on:
  push:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Baixa seu código
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. CONSTRÓI O APK (Usando uma máquina pronta/Docker)
      # Isso elimina erros de instalação de Linux
      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          workdir: frontend
          buildozer_version: stable

      # 3. Envia o arquivo para você baixar
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: getline-apk
          path: frontend/bin/*.apk